server:
  port: 8081

  spring:
    jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: create-drop
    datasource:
      driverClassName: org.postgresql.Driver
      platform: postgres
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: your_password
